version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8881:80
    volumes:
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/www/data